import { chromium } from "playwright";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
const root = "/Users/lucy/Projects/wordpress-support-reproduction-engine";
const out = resolve(root, "docs/screenshots");
const ssr = readFileSync(resolve(root, "fixtures/ssr/13-php-below-woo-requirement.txt"), "utf8");
const l1 = readFileSync(resolve(root, "fixtures/logs/log-01-plugin-fatal.txt"), "utf8");
const l2 = readFileSync(resolve(root, "fixtures/logs/log-02-theme-fatal.txt"), "utf8");
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1280, height: 1000 } });
await p.goto("http://localhost:5174/", { waitUntil: "networkidle" });
await p.fill("#artifact", `${ssr}\n${l1}\n${l2}`);
await p.click("#analyse");
await p.waitForSelector(".finding");
const cards = p.locator("#results > .card");
await cards.nth(0).screenshot({ path: resolve(out, "04-environment.png") });
await cards.nth(1).screenshot({ path: resolve(out, "05-findings.png") });
await cards.nth(2).screenshot({ path: resolve(out, "06-reproducibility.png") });
console.log("ok");
await b.close();
